Script started on Fri 29 Jul 2022 09:03:29 PM PDT
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm sharpen.ppm hue.ppm noise.ppm posterize.ppm blur.ppm libFilter.a libFileIO.a
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ ls -la
total 888
drwxr-xr-x.  2 chpeters ugrad   4096 Jul 29 21:02 [0m[01;34m.[0m
drwx--x--x. 14 chpeters ugrad   4096 Jul 29 21:00 [01;34m..[0m
-rw-r--r--.  1 chpeters ugrad   6056 Jul 28 22:23 AdvancedB2.c
-rw-r--r--.  1 chpeters ugrad   3186 Jul 28 08:54 AdvancedB.c
-rw-r--r--.  1 chpeters ugrad    696 Jul 28 08:54 AdvancedB.h
-rw-r--r--.  1 chpeters ugrad   6049 Jul 29 15:51 Advanced.c
-rw-r--r--.  1 chpeters ugrad    724 Jul 29 09:04 Advanced.h
-rw-r--r--.  1 chpeters ugrad 720015 Jul 28 13:32 [01;35mapplestore.ppm[0m
-rw-r--r--.  1 chpeters ugrad    664 Jul 25 10:16 Constants.h
-rw-r--r--.  1 chpeters ugrad   3588 Jul 28 22:23 DIPsB2.c
-rw-r--r--.  1 chpeters ugrad   3588 Jul 28 08:54 DIPsB.c
-rw-r--r--.  1 chpeters ugrad    406 Jul 28 08:55 DIPsB.h
-rw-r--r--.  1 chpeters ugrad   3728 Jul 29 13:32 DIPs.c
-rw-r--r--.  1 chpeters ugrad    362 Jul 29 09:05 DIPs.h
-rw-r--r--.  1 chpeters ugrad   4335 Jul 28 08:55 FileIOB.c
-rw-r--r--.  1 chpeters ugrad   1552 Jul 28 08:55 FileIOB.h
-rw-r--r--.  1 chpeters ugrad   4335 Jul 29 09:20 FileIO.c
-rw-r--r--.  1 chpeters ugrad   1532 Jul 29 09:03 FileIO.h
-rw-r--r--.  1 chpeters ugrad   4263 Jul 28 08:55 ImageB.c
-rw-r--r--.  1 chpeters ugrad   1744 Jul 28 08:55 ImageB.h
-rw-r--r--.  1 chpeters ugrad   4577 Jul 29 11:17 Image.c
-rw-r--r--.  1 chpeters ugrad   1744 Jul 25 10:16 Image.h
-rw-r--r--.  1 chpeters ugrad    217 Jul 24 21:47 ListOfStudents.txt
-rw-r--r--.  1 chpeters ugrad   2761 Jul 29 10:07 Makefile
-rwxr-xr-x.  1 chpeters ugrad  14176 Jul 24 22:01 [01;32mNewStudentList[0m
-rw-r--r--.  1 chpeters ugrad   6323 Jul 24 22:57 NewStudentList.c
-rw-r--r--.  1 chpeters ugrad   5216 Jul 24 14:00 NSLBack.c
-rw-r--r--.  1 chpeters ugrad   7455 Jul 28 22:24 PhotoLabB2.c
-rw-r--r--.  1 chpeters ugrad   6654 Jul 28 08:56 PhotoLabB.c
-rw-r--r--.  1 chpeters ugrad   7376 Jul 29 16:05 PhotoLab.c
-rw-r--r--.  1 chpeters ugrad      0 Jul 29 21:03 PhotoLab.script
-rw-r--r--.  1 chpeters ugrad   3412 Jul 28 08:56 TestB.c
-rw-r--r--.  1 chpeters ugrad   3398 Jul 29 15:55 Test.c
-rw-r--r--.  1 chpeters ugrad    610 Jul 25 10:16 Test.h
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ make
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -ansi -std=c99 -Wall -c -DDEBUG -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c -DDEBUG -c Test.c -o Test.o
gcc -ansi -std=c99 -Wall PhotoLab.o FileIO.o Image.o DIPs.o Advanced.o Test.o -L. -lFilter -o PhotoLab -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall PhotoLab_DEBUG.o FileIO.o Image.o Advanced.o DIPs.o Test.o -L. -lFilter -o PhotoLabTest -lm
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ ./PhotoLab

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add Noise to an image
7: Posterize an image
8: Motion blur an image
9: Enlarge the picture by percentage
10: Crop a square portion of the image
11: Adjust the Brightness and Contrast of an image
12: Test all functions
13: Exit

-------------------------
Please make your choice: 12
LoadImage & SaveImage tested!

Black and White tested!

Sharpen Detection tested!

Hue tested!

Noise tested!

Posterization tested!

MotionBlur tested!

Enlarge tested!

Square tested!

Brightness and Contrast tested!

AutoTest finished successfully
-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add Noise to an image
7: Posterize an image
8: Motion blur an image
9: Enlarge the picture by percentage
10: Crop a square portion of the image
11: Adjust the Brightness and Contrast of an image
12: Test all functions
13: Exit

-------------------------
Please make your choice: 13
You exit the program.
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ valgrind --leak-check=full ./PhotoLabTest
==2273== Memcheck, a memory error detector
==2273== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==2273== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==2273== Command: ./PhotoLabTest
==2273== 
LoadImage & SaveImage tested!

Black and White tested!

Sharpen Detection tested!

Hue tested!

Noise tested!

Posterization tested!

MotionBlur tested!

Enlarge tested!

Square tested!

Brightness and Contrast tested!

==2273== 
==2273== HEAP SUMMARY:
==2273==     in use at exit: 0 bytes in 0 blocks
==2273==   total heap usage: 72 allocs, 72 frees, 10,492,576 bytes allocated
==2273== 
==2273== All heap blocks were freed -- no leaks are possible
==2273== 
==2273== For lists of detected and suppressed errors, rerun with: -s
==2273== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ cp[K[Kmake clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm sharpen.ppm hue.ppm noise.ppm posterize.ppm blur.ppm libFilter.a libFileIO.a
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ ls -la
total 4804
drwxr-xr-x.  2 chpeters ugrad    4096 Jul 29 21:06 [0m[01;34m.[0m
drwx--x--x. 14 chpeters ugrad    4096 Jul 29 21:00 [01;34m..[0m
-rw-r--r--.  1 chpeters ugrad    6056 Jul 28 22:23 AdvancedB2.c
-rw-r--r--.  1 chpeters ugrad    3186 Jul 28 08:54 AdvancedB.c
-rw-r--r--.  1 chpeters ugrad     696 Jul 28 08:54 AdvancedB.h
-rw-r--r--.  1 chpeters ugrad    6049 Jul 29 15:51 Advanced.c
-rw-r--r--.  1 chpeters ugrad     724 Jul 29 09:04 Advanced.h
-rw-r--r--.  1 chpeters ugrad  720015 Jul 28 13:32 [01;35mapplestore.ppm[0m
-rw-r--r--.  1 chpeters ugrad  720015 Jul 29 21:05 [01;35mbrightnessandcontrast.ppm[0m
-rw-r--r--.  1 chpeters ugrad     664 Jul 25 10:16 Constants.h
-rw-r--r--.  1 chpeters ugrad    3588 Jul 28 22:23 DIPsB2.c
-rw-r--r--.  1 chpeters ugrad    3588 Jul 28 08:54 DIPsB.c
-rw-r--r--.  1 chpeters ugrad     406 Jul 28 08:55 DIPsB.h
-rw-r--r--.  1 chpeters ugrad    3728 Jul 29 13:32 DIPs.c
-rw-r--r--.  1 chpeters ugrad     362 Jul 29 09:05 DIPs.h
-rw-r--r--.  1 chpeters ugrad 2080816 Jul 29 21:05 [01;35menlarge.ppm[0m
-rw-r--r--.  1 chpeters ugrad    4335 Jul 28 08:55 FileIOB.c
-rw-r--r--.  1 chpeters ugrad    1552 Jul 28 08:55 FileIOB.h
-rw-r--r--.  1 chpeters ugrad    4335 Jul 29 09:20 FileIO.c
-rw-r--r--.  1 chpeters ugrad    1532 Jul 29 09:03 FileIO.h
-rw-r--r--.  1 chpeters ugrad    4263 Jul 28 08:55 ImageB.c
-rw-r--r--.  1 chpeters ugrad    1744 Jul 28 08:55 ImageB.h
-rw-r--r--.  1 chpeters ugrad    4577 Jul 29 11:17 Image.c
-rw-r--r--.  1 chpeters ugrad    1744 Jul 25 10:16 Image.h
-rw-r--r--.  1 chpeters ugrad     217 Jul 24 21:47 ListOfStudents.txt
-rw-r--r--.  1 chpeters ugrad    2761 Jul 29 10:07 Makefile
-rwxr-xr-x.  1 chpeters ugrad   14176 Jul 24 22:01 [01;32mNewStudentList[0m
-rw-r--r--.  1 chpeters ugrad    6323 Jul 24 22:57 NewStudentList.c
-rw-r--r--.  1 chpeters ugrad    5216 Jul 24 14:00 NSLBack.c
-rw-r--r--.  1 chpeters ugrad  720015 Jul 29 21:04 [01;35moriginal.ppm[0m
-rw-r--r--.  1 chpeters ugrad    7455 Jul 28 22:24 PhotoLabB2.c
-rw-r--r--.  1 chpeters ugrad    6654 Jul 28 08:56 PhotoLabB.c
-rw-r--r--.  1 chpeters ugrad    7376 Jul 29 16:05 PhotoLab.c
-rw-r--r--.  1 chpeters ugrad       0 Jul 29 21:03 PhotoLab.script
-rw-r--r--.  1 chpeters ugrad  480015 Jul 29 21:05 [01;35msquare.ppm[0m
-rw-r--r--.  1 chpeters ugrad    3412 Jul 28 08:56 TestB.c
-rw-r--r--.  1 chpeters ugrad    3398 Jul 29 15:55 Test.c
-rw-r--r--.  1 chpeters ugrad     610 Jul 25 10:16 Test.h
]0;chpeters@crystalcove:~/hw4[chpeters@crystalcove ~/hw4]$ exit
exit

Script done on Fri 29 Jul 2022 09:07:03 PM PDT
